### ISSUE TITLE
Add a Close operation

### ISSUE THREAD

**Issue by hallyn** [radu-munteanu/fsnotify#1]
It would be great to have a Close operation, mapped to (IN_CLOSE_WRITE|IN_CLOSE_NOWRITE), as in

https://github.com/hallyn/fsnotify/commit/fe32dd0ead607ba4b7ba72da8d5d5ae2b07d2325

**Comment by radu-munteanu** [comment]
Implemented in commit https://github.com/radu-munteanu/fsnotify/commit/05c96b6df572313361fafd28a83956cf8eabb61a

**Comment by radu-munteanu** [comment]
Note that this Op is implemented only for inotify

**Comment by radu-munteanu** [comment]
Second note: if you cloned this internally, before this message post, please re-clone. I did a rebase in order to get a missing commit from upstream (https://github.com/fsnotify/fsnotify/commit/a904159b9206978bb6d53fcc7a769e5cd726c737), and not make an extra commit for the merge.

**Comment by radu-munteanu** [comment]
@hallyn did it worked for you? 🥇

**Comment by hallyn** [comment]
On Thu, Feb 09, 2017 at 01:08:46AM -0800, Radu Munteanu wrote:
> @hallyn did it worked for you? 🥇 

Yes, thank you.

**Comment by radu-munteanu** [comment]
Hi @hallyn, I have an update: I've branched out these commits (branch 2019) in order to keep the old hashes for projects with old dependencies. On master, I've pulled the newest upstream commits and made a new commit with the operations changes, also updating the go.mod for this fork. For go mod integration the following line should be used:
```
github.com/radu-munteanu/fsnotify v.1.2020.0
```
@coltonf93, @rubenhazelaar you should update your forks, if you need the latest commits from fsnotify/fsnotify.

**Comment by radu-munteanu** [comment]
I've updated the commit a minute ago, in order to have a proper commit message.
